name: Magic Backend Deploy
run-name: ${{ inputs.backend_repo}} - ${{ inputs.release_env }}

permissions: write-all

on:
  workflow_call:
    inputs:
      working_dir:
        required: false
        description: "Operating path for path dependent steps"
        type: string
        default: .
      node_versions:
        required: false
        description: "List of node version which want to scan"
        type: string
        default: "['20.14.0']" #"['18.16']"
      release_env:
        description: 'Release Environment'
        required: true
        default: ""
        type: string
      release_version:
        description: 'Release Version'
        required: true
        default: ""
        type: string
      backend_repo:
        description: 'backend Repo'
        required: true
        default: ""
        type: string
      target_branch:
          description: 'Target Branch'
          required: true
          default: ""
          type: string
      target_version:
          description: 'Target Version'
          required: false
          default: ""
          type: string


jobs:     
  build-backend-and-push-to-s3:
    name: ${{ inputs.backend_repo}} ${{inputs.target_branch}} Build and push artifact to s3
    if: ${{ inputs.backend_repo == 'magic-common-backend' }}
    uses: ./.github/workflows/job_magic_backend_build.yaml
    with:
      working_dir: ./
      release_env: ${{ inputs.release_env }}
      backend_repo: ${{ inputs.backend_repo }}
      target_branch: ${{ inputs.target_branch }}
      release_version: ${{ inputs.release_version }}
      target_version: ${{ inputs.target_version }}
    secrets: inherit

  build-external-backend-and-push-to-s3:
    name: ${{ inputs.backend_repo}} ${{inputs.target_branch}} Build and push artifact to s3
    if: ${{ inputs.backend_repo == 'datahub-external-api' }}
    uses: ./.github/workflows/job_magic_external_backend_build.yaml
    with:
      working_dir: ./
      release_env: ${{ inputs.release_env }}
      backend_repo: ${{ inputs.backend_repo }}
      target_branch: ${{ inputs.target_branch }}
      release_version: ${{ inputs.release_version }}
      target_version: ${{ inputs.target_version }}
    secrets: inherit