name: Magic Frontend Deploy
run-name: Magic Frontend Deploy - ${{ inputs.release_env }}

permissions: write-all

on:
  workflow_call:
    inputs:
      working_dir:
        required: false
        description: "Operating path for path dependent steps"
        type: string
        default: .
      node_versions:
        required: false
        description: "List of node version which want to scan"
        type: string
        default: "['20.14.0']" #"['18.16']"
      release_env:
        description: 'Release Environment'
        required: true
        default: ""
        type: string
      release_version:
        description: 'Release Version'
        required: true
        default: ""
        type: string
      frontend_repo:
        description: 'Frontend Repo'
        required: true
        default: ""
        type: string
      target_branch:
          description: 'Target Branch'
          required: true
          default: ""
          type: string
      target_version:
          description: 'Target Version'
          required: false
          default: ""
          type: string

jobs:
  # statitic-analysis-toolbox:
  #   name: Analysis code quality
  #   if: ${{ inputs.target_branch == 'release' && inputs.frontend_repo == 'magic-toolbox-frontend' }}
  #   uses: ./.github/workflows/static-analysis.yaml
  #   with:
  #     REPO_NAME: ${{ inputs.frontend_repo }}
  #     BUILD_PATH: apps/toolbox
  #     QUALITY_REPORT: true
  #     STREAM: magic-${{ inputs.frontend_repo }}}}
  #     environment: main
  #   secrets:
  #     GH_MANAGEPACKAGE_TOKEN: ${{ secrets.GH_MANAGEPACKAGE_TOKEN }}

  # statitic-analysis-datahub:
  #   name: Analysis code quality
  #   if: ${{ inputs.target_branch == 'release' && inputs.frontend_repo == 'magic-cms-frontend' }}
  #   uses: ./.github/workflows/static-analysis.yaml
  #   with:
  #     REPO_NAME: ${{ inputs.frontend_repo }}
  #     BUILD_PATH: ./
  #     QUALITY_REPORT: true
  #     STREAM: magic-${{ inputs.frontend_repo }}}}
  #     environment: main
  #   secrets:
  #     GH_MANAGEPACKAGE_TOKEN: ${{ secrets.GH_MANAGEPACKAGE_TOKEN }}

  toolbox-build-and-release:
    name: ${{ inputs.frontend_repo}} ${{inputs.target_branch}} Build and release
    if: ${{ inputs.frontend_repo == 'magic-toolbox-frontend' }}
    uses: ./.github/workflows/job_toolbox_frontend_build.yaml
    with:
      working_dir: ./apps/toolbox
      release_env: ${{ inputs.release_env }}
      frontend_repo: ${{ inputs.frontend_repo }}
      target_branch: ${{ inputs.target_branch }}
      release_version: ${{ inputs.release_version }}
      target_version: ${{ inputs.target_version }}
    secrets: inherit

  datahub-build-and-release:
    name: ${{ inputs.frontend_repo}} ${{inputs.target_branch}} Build and release
    if: ${{ inputs.frontend_repo == 'magic-cms-frontend' }}
    uses: ./.github/workflows/job_datahub_frontend_build.yaml
    with:
      working_dir: ./
      release_env: ${{ inputs.release_env }}
      frontend_repo: ${{ inputs.frontend_repo }}
      target_branch: ${{ inputs.target_branch }}
      release_version: ${{ inputs.release_version }}
      target_version: ${{ inputs.target_version }}
    secrets: inherit